config/routes.rb
Rails.application.routes.draw do
  resources :goods
  root to: 'main#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/good.rb
class Good < ApplicationRecord
  has_attached_file :image, styles: {medium: "300x300>", thumb: "50x50>"},
                    url: "/assets/products/:id/:style/:basename.:extension",
                    path: ":rails_root/public/assets/products/:id/:style/:basename.:extension",
                    default_url: "http://1.bp.blogspot.com/-LJv5_H0e5nM/UzAqr7as75I/AAAAAAAAAsM/f9_6eUuUuo8/s1600/clothes+1.png"

  validates_attachment_size :image, :less_than => 5.megabytes
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :name, presence: true

  scope :winter, -> { where(season: 0) }
  scope :spring, -> { where(season: 1) }
  scope :summer, -> { where(season: 2) }
  scope :autumn, -> { where(season: 3) }



  def self.seasons (h = false)
    if h
      { winter: 0, spring: 1, summer: 2, autumn: 3 }
    else
      [['Winter', 0], ['Spring', 1], ['Summer', 2], ['Autumn', 3]]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :set_good, only: [:show, :edit, :update, :destroy]

  # GET /goods
  # GET /goods.json
  def index
    if !params[:season_id].present?
      @goods = Good.all
    else
        @goods = Good.where(season: params[:season_id])
        @current_season = params[:season_id]
    end
  end

  # GET /goods/1
  # GET /goods/1.json
  def show
  end

  # GET /goods/new
  def new
    @good = Good.new
  end

  # GET /goods/1/edit
  def edit
  end

  # POST /goods
  # POST /goods.json
  def create
    @good = Good.new(good_params)

    respond_to do |format|
      if @good.save
        format.html { redirect_to @good, notice: 'Good was successfully created.' }
        format.json { render :show, status: :created, location: @good }
      else
        format.html { render :new }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goods/1
  # PATCH/PUT /goods/1.json
  def update
    @good = Good.find(params[:id])
    respond_to do |format|
      if @good.update(good_params)
        format.html { redirect_to @good, notice: 'Good was successfully updated.' }
        format.json { render :show, status: :ok, location: @good }
      else
        format.html { render :edit }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goods/1
  # DELETE /goods/1.json
  def destroy
    @good.destroy
    respond_to do |format|
      format.html { redirect_to goods_url, notice: 'Good was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_good
    @good = Good.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def good_params
    params.require(:good).permit(:name, :description, :season, :image)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/goods/_form.html.erb
<%= form_for good, html:{ class:"form-horizontal" }  do |f| %>
    <% if good.errors.any? %>
        <div id="error_explanation" class="alert alert-danger alert-dismissible" role="alert">
          <h2><%= pluralize(good.errors.count, "error") %> prohibited this good from being saved:</h2>

          <ul>
            <% good.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="form-group">
      <%= f.label :name, class:"col-xs-3 col-md-1" %>
      <%= content_tag(:div, class:"col-xs-8 col-md-4") do %>
          <%= f.text_field :name, class:"form-control", placeholder:"Name" %>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.label :description, class:"col-xs-3 col-md-1" %>
      <%= content_tag(:div, class:"col-xs-8 col-md-4") do %>
        <%= f.text_field :description, class:"form-control", placeholder:"Description" %>
      <% end %>

    </div>

    <div class="form-group">
      <%= f.label :season, class:"col-xs-3 col-md-1" %>
      <%= content_tag(:div, class:"col-xs-8 col-md-4") do %>
          <%= select_tag("good[season]", options_for_select([['Winter', 0], ['Spring', 1], ['Summer', 2], ['Autumn', 3]], good.season), class:"form-control") %>
      <% end %>

    </div>

    <div class="form-group">
      <%= f.label :image, class:"col-xs-3 col-md-1" %>
      <%= content_tag(:div, class:"col-xs-8 col-md-6") do %>
        <%= f.file_field :image %>
      <% end %>

    </div>

    <div class="form-group">
      <%= f.submit class:"btn btn-primary col-xs-4 col-xs-offset-4 col-md-1 col-md-offset-2" %>
    </div>
<% end %>

app/views/goods/edit.html.erb
<h1>Editing Good</h1>

<div class="jumbotron">

    <%= render 'form', good: @good %>
    <%= link_to 'Show', @good, id: "show" %> |
    <%= link_to 'Back', goods_path, id: "back" %>
</div>

app/views/goods/index.html.erb
<p id="notice"><%= notice %></p>

<h3 align="center">Goods</h3>

<div class="row">
    <%= form_tag({},:method => :get, class: 'season_selector col-xs-10 col-xs-offset-1  col-md-2 col-md-offset-0') do %>
        <%=select_tag( :season_id,
                       options_for_select(Good.seasons, @current_season),
                       include_blank: "All",
                       onchange: "this.form.submit();",
                       class:"form-control") %>
    <% end %>
</div>

<div class="row">
  <span>&nbsp;</span>
</div>
<% @goods.each do |good| %>
    <%= content_tag(:div, id:"good-#{good.id}") do%>
        <%= content_tag(:div, class:"col-xs-6 col-md-2 pull-left") do%>
            <%= content_tag(:div, class:"thumbnail") do%>
                <%= content_tag(:a, href: good_path(good)) do %>
                    <%= image_tag(good.image.url(:medium), class:"img-thumbnail") %>
                <%end%>
                <%= content_tag(:div, class:"caption") do%>
                    <%= content_tag(:h4, good.name) %>
                    <%= content_tag(:p, good.description) %>
                    <%= content_tag(:p) do %>
                        <%= link_to "Edit", edit_good_path(good), class:"btn btn-primary btn-block btn-xs", role:"button" %>
                        <%= link_to 'Destroy', good, method: :delete, data: {confirm: 'Are you sure?'}, class:"btn btn-primary btn-block btn-xs", role:"button" %>
                    <%end%>
                <%end%>
            <%end%>
        <%end%>
    <%end%>
<%end%>

app/views/goods/new.html.erb
<h1>New Good</h1>

<div class="jumbotron">
    <%= render 'form', good: @good %>
    <%= link_to 'Back', goods_path %>
</div>

app/views/goods/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron col-md-4 col-md-offset-4">
    <p>
      <strong>Name:</strong>
      <%= @good.name %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @good.description %>
    </p>

    <p>
      <strong>Season:</strong>
      <%= Good.seasons(true).key(@good.season.to_i).capitalize %>
    </p>

    <p>
        <%= image_tag @good.image.url(:medium), class: "thumbnail col-xs-12", data:{toggle: "modal", target:".bs-example-modal-lg"} %>
    </p>

    <%= link_to 'Edit', edit_good_path(@good), id: "edit", role:"button", class: "btn btn-default col-xs-4 col-xs-offset-1" %> &nbsp;
    <%= link_to 'Back', goods_path, id: "back", role:"button", class: "btn btn-default col-xs-4 col-xs-offset-2" %>
</div>


<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
        <div class="modal-body">
          <%= image_tag @good.image.url(:original), class: "thumbnail", width: "100%" %>
        </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wardrobe</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Wardrobe", root_path, class:"navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "List of goods", goods_path%></li>
          <li><%=link_to "Add Good", new_good_path %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container-fluid">
    <%= yield %>
  </div>
  </body>
</html>

app/views/main/show.html.erb
<h3>Wellcome to the App</h3>


<%= link_to 'Show goods', goods_path, class:"btn btn-primary btn-block", role:"button" %>